name: "Environment Deploy - Terraform"

on:
  # Trigger whenever code changes under environments/qa or environments/production
  push:
    paths:
      - "environments/qa/**"
      - "environments/production/**"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_UNBOUNDSHARE }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_UNBOUNDSHARE }}
  AWS_REGION: "ap-southeast-2" # Your Singapore Region

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_folder: [environments/qa, environments/production]

    defaults:
      run:
        working-directory: ${{ matrix.env_folder }}

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan

      - name: "Terraform Apply"
        run: terraform apply -auto-approve